app:
  config:
    topic-name: avro-topic
    group-id: avro-group

spring:
  application:
    name: KafkaSchemaRegistryAvro
  kafka:
    consumer:
      group-id: avro-group
      bootstrap-servers: localhost:29092
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    producer:
      client-id: avro-client-id
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema.registry.url: http://localhost:8090
      specific.avro.reader: true